In [71]:
import pandas as pd
data = pd.read_csv('data/students.csv')
data = data.dropna() # opcionalno
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
4,male,group C,some college,standard,none,76.0,78.0,75.0
6,female,group B,some college,standard,completed,88.0,95.0,92.0
8,male,group D,high school,free/reduced,completed,64.0,64.0,67.0

In [72]:
data.shape

(996, 8)

In [73]:
X_cols = ['gender', 'race/ethnicity', 'math score', 'reading score']
y_col = 'writing score'

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_temp, y_train, y_temp = train_test_split(data[X_cols], data[y_col], train_size=0.6)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, train_size=0.5)

In [75]:
from sklearn.preprocessing import LabelEncoder
le_gender = LabelEncoder()
le_race = LabelEncoder()

X_train['gender'] = le_gender.fit_transform(X_train['gender'])
X_train['race/ethnicity'] = le_race.fit_transform(X_train['race/ethnicity'])

In [76]:
X_test['gender'] = le_gender.transform(X_test['gender'])
X_val['gender'] = le_gender.transform(X_val['gender'])

X_test['race/ethnicity'] = le_race.transform(X_test['race/ethnicity'])
X_val['race/ethnicity'] = le_race.transform(X_val['race/ethnicity'])

In [77]:
X_train.head()

     gender  race/ethnicity  math score  reading score
74        1               2        49.0           49.0
192       0               1        62.0           64.0
115       1               2        84.0           77.0
219       1               1        61.0           56.0
424       1               1        41.0           39.0

In [78]:
import joblib
joblib.dump(le_gender, 'artifacts/le_gender.pkl')
joblib.dump(le_race, 'artifacts/le_race.pkl')

['artifacts/le_race.pkl']

In [79]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X_val)

In [80]:
joblib.dump(scaler, 'artifacts/std_scaler_X.pkl')

['artifacts/std_scaler_X.pkl']

In [81]:
y_train_2d = y_train.to_numpy().reshape(-1,1)
y_val_2d = y_val.to_numpy().reshape(-1,1)
y_test_2d = y_test.to_numpy().reshape(-1,1)

In [99]:
scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train_2d)
y_val = scaler_y.transform(y_val_2d)
y_test = scaler_y.transform(y_test_2d)

In [100]:
joblib.dump(scaler_y, 'artifacts/std_scaler_y.pkl')

['artifacts/std_scaler_y.pkl']

In [85]:
# Prelazimo na drugi dio - izgradnja modela

In [88]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential, layers

In [89]:
input_shape = X_train.shape[1]

In [90]:
basic_model = Sequential([
    layers.Input(shape=(input_shape,)),
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='tanh'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

In [91]:
from keras.optimizers import Adam

basic_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mse", metrics=["mae"])

In [92]:
basic_model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=50, batch_size=32)

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.6252 - mae: 0.6163 - val_loss: 0.1603 - val_mae: 0.3209
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1585 - mae: 0.3169 - val_loss: 0.1243 - val_mae: 0.2876
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1245 - mae: 0.2772 - val_loss: 0.0933 - val_mae: 0.2461
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1061 - mae: 0.2603 - val_loss: 0.0917 - val_mae: 0.2465
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1086 - mae: 0.2614 - val_loss: 0.0933 - val_mae: 0.2438
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1020 - mae: 0.2586 - val_loss: 0.0904 - val_mae: 0.2419
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1110 - mae: 0.2671 - val_loss: 0.0903 - val_mae: 0.2440
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1141 - mae: 0.2679 - val_loss: 0.0920 - val_mae: 0.2451
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1087 - mae: 0.2576 - val_loss: 0.0875 - val_mae: 0.2410
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0966 - mae: 0.2438 - val_loss: 0.0906 - val_mae: 0.2425
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1090 - mae: 0.2590 - val_loss: 0.0883 - val_mae: 0.2432
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1081 - mae: 0.2625 - val_loss: 0.0881 - val_mae: 0.2416
Epoch 13/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1081 - mae: 0.2619 - val_loss: 0.0842 - val_mae: 0.2375
Epoch 14/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1048 - mae: 0.2579 - val_loss: 0.0840 - val_mae: 0.2364
Epoch 15/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1006 - mae: 0.2496 - val_loss: 0.0842 - val_mae: 0.2377
Epoch 16/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0972 - mae: 0.2483 - val_loss: 0.0858 - val_mae: 0.2410
Epoch 17/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1030 - mae: 0.2560 - val_loss: 0.0847 - val_mae: 0.2365
Epoch 18/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0990 - mae: 0.2517 - val_loss: 0.0873 - val_mae: 0.2397
Epoch 19/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1060 - mae: 0.2607 - val_loss: 0.0856 - val_mae: 0.2386
Epoch 20/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0928 - mae: 0.2442 - val_loss: 0.0874 - val_mae: 0.2427
Epoch 21/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0995 - mae: 0.2541 - val_loss: 0.0854 - val_mae: 0.2377
Epoch 22/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1003 - mae: 0.2550 - val_loss: 0.0855 - val_mae: 0.2387
Epoch 23/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0899 - mae: 0.2393 - val_loss: 0.0894 - val_mae: 0.2417
Epoch 24/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1011 - mae: 0.2530 - val_loss: 0.0867 - val_mae: 0.2377
Epoch 25/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0927 - mae: 0.2417 - val_loss: 0.0878 - val_mae: 0.2377
Epoch 26/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0980 - mae: 0.2590 - val_loss: 0.0893 - val_mae: 0.2459
Epoch 27/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0884 - mae: 0.2390 - val_loss: 0.0855 - val_mae: 0.2368
Epoch 28/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0928 - mae: 0.2462 - val_loss: 0.0898 - val_mae: 0.2475
Epoch 29/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0966 - mae: 0.2478 - val_loss: 0.0874 - val_mae: 0.2381
Epoch 30/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0925 - mae: 0.2448 - val_loss: 0.0874 - val_mae: 0.2386
Epoch 31/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0908 - mae: 0.2402 - val_loss: 0.0883 - val_mae: 0.2434
Epoch 32/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0925 - mae: 0.2399 - val_loss: 0.0852 - val_mae: 0.2368
Epoch 33/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0860 - mae: 0.2411 - val_loss: 0.0889 - val_mae: 0.2427
Epoch 34/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0883 - mae: 0.2399 - val_loss: 0.0856 - val_mae: 0.2365
Epoch 35/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0923 - mae: 0.2446 - val_loss: 0.0899 - val_mae: 0.2437
Epoch 36/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0895 - mae: 0.2393 - val_loss: 0.0874 - val_mae: 0.2393
Epoch 37/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0864 - mae: 0.2337 - val_loss: 0.0874 - val_mae: 0.2376
Epoch 38/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0927 - mae: 0.2430 - val_loss: 0.0948 - val_mae: 0.2472
Epoch 39/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0932 - mae: 0.2410 - val_loss: 0.0851 - val_mae: 0.2341
Epoch 40/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0934 - mae: 0.2431 - val_loss: 0.0914 - val_mae: 0.2401
Epoch 41/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0902 - mae: 0.2425 - val_loss: 0.0913 - val_mae: 0.2457
Epoch 42/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0907 - mae: 0.2451 - val_loss: 0.0920 - val_mae: 0.2433
Epoch 43/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0877 - mae: 0.2385 - val_loss: 0.0923 - val_mae: 0.2436
Epoch 44/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0876 - mae: 0.2382 - val_loss: 0.0868 - val_mae: 0.2365
Epoch 45/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0883 - mae: 0.2354 - val_loss: 0.0908 - val_mae: 0.2466
Epoch 46/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0891 - mae: 0.2368 - val_loss: 0.0931 - val_mae: 0.2430
Epoch 47/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0829 - mae: 0.2307 - val_loss: 0.0953 - val_mae: 0.2514
Epoch 48/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0863 - mae: 0.2361 - val_loss: 0.0881 - val_mae: 0.2378
Epoch 49/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0865 - mae: 0.2323 - val_loss: 0.0997 - val_mae: 0.2568
Epoch 50/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0909 - mae: 0.2399 - val_loss: 0.0905 - val_mae: 0.2419

In [93]:
basic_model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0816 - mae: 0.2299

[0.0815548226237297, 0.2298654019832611]

In [101]:
y_pred = basic_model.predict(X_test)
y_pred[:5]

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[ 0.32648298],
       [ 0.575659  ],
       [ 0.16628182],
       [-0.00936596],
       [ 0.3811488 ]], dtype=float32)

In [102]:
y_pred = scaler_y.inverse_transform(y_pred)
y_pred[:5]

array([[72.71676 ],
       [76.434265],
       [70.32668 ],
       [67.70616 ],
       [73.53233 ]], dtype=float32)

In [103]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import regularizers

advanced_model = Sequential([
    layers.Input(shape=(input_shape,)),
    layers.Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.BatchNormalization(),
    layers.Dense(1024, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(256, activation='tanh'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

In [105]:
advanced_model.compile(optimizer=Adam(0.01), loss="mse", metrics=["mae"])

In [107]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True,
    verbose=1
)

In [108]:
advanced_model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=1000, batch_size=32,
                   callbacks=[early_stopping])

Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 2.3410 - mae: 1.0030 - val_loss: 6.3361 - val_mae: 2.3827
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6909 - mae: 0.5902 - val_loss: 3.9599 - val_mae: 1.8793
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4409 - mae: 0.4230 - val_loss: 1.5910 - val_mae: 1.1056
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3716 - mae: 0.3816 - val_loss: 0.9787 - val_mae: 0.8174
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3618 - mae: 0.3865 - val_loss: 0.9255 - val_mae: 0.8156
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3060 - mae: 0.3522 - val_loss: 0.4787 - val_mae: 0.5246
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2842 - mae: 0.3498 - val_loss: 0.2856 - val_mae: 0.3569
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3022 - mae: 0.3634 - val_loss: 0.2514 - val_mae: 0.3257
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2636 - mae: 0.3385 - val_loss: 0.3534 - val_mae: 0.4151
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3108 - mae: 0.3743 - val_loss: 0.5688 - val_mae: 0.5788
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3046 - mae: 0.3642 - val_loss: 0.8201 - val_mae: 0.7151
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2827 - mae: 0.3643 - val_loss: 0.2988 - val_mae: 0.3796
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3193 - mae: 0.3933 - val_loss: 0.5449 - val_mae: 0.5710
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3414 - mae: 0.4066 - val_loss: 0.3404 - val_mae: 0.3856
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2820 - mae: 0.3471 - val_loss: 0.3208 - val_mae: 0.3847
Epoch 16/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3148 - mae: 0.3817 - val_loss: 0.2570 - val_mae: 0.3373
Epoch 17/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2643 - mae: 0.3464 - val_loss: 0.2292 - val_mae: 0.3243
Epoch 18/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2585 - mae: 0.3452 - val_loss: 0.2936 - val_mae: 0.3834
Epoch 19/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2537 - mae: 0.3415 - val_loss: 0.2278 - val_mae: 0.3198
Epoch 20/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2351 - mae: 0.3360 - val_loss: 0.2704 - val_mae: 0.3674
Epoch 21/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2578 - mae: 0.3551 - val_loss: 0.2107 - val_mae: 0.3183
Epoch 22/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2262 - mae: 0.3282 - val_loss: 0.2865 - val_mae: 0.3992
Epoch 23/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2233 - mae: 0.3269 - val_loss: 0.2648 - val_mae: 0.3861
Epoch 24/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2625 - mae: 0.3660 - val_loss: 0.1971 - val_mae: 0.3018
Epoch 25/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2341 - mae: 0.3305 - val_loss: 0.2410 - val_mae: 0.3506
Epoch 26/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2625 - mae: 0.3601 - val_loss: 0.2282 - val_mae: 0.3343
Epoch 27/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2313 - mae: 0.3373 - val_loss: 0.2796 - val_mae: 0.3721
Epoch 28/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2245 - mae: 0.3238 - val_loss: 0.2894 - val_mae: 0.4034
Epoch 29/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2553 - mae: 0.3656 - val_loss: 0.2914 - val_mae: 0.4045
Epoch 30/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2741 - mae: 0.3762 - val_loss: 0.2560 - val_mae: 0.3632
Epoch 31/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2300 - mae: 0.3415 - val_loss: 0.2002 - val_mae: 0.3101
Epoch 32/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2156 - mae: 0.3273 - val_loss: 0.1792 - val_mae: 0.2979
Epoch 33/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2207 - mae: 0.3445 - val_loss: 0.1879 - val_mae: 0.3171
Epoch 34/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2121 - mae: 0.3269 - val_loss: 0.1805 - val_mae: 0.3025
Epoch 35/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2477 - mae: 0.3599 - val_loss: 0.2787 - val_mae: 0.3815
Epoch 36/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2899 - mae: 0.3951 - val_loss: 0.2372 - val_mae: 0.3489
Epoch 37/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2363 - mae: 0.3314 - val_loss: 0.2145 - val_mae: 0.3135
Epoch 38/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2387 - mae: 0.3388 - val_loss: 0.2070 - val_mae: 0.3218
Epoch 39/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2443 - mae: 0.3500 - val_loss: 0.2276 - val_mae: 0.3546
Epoch 40/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2834 - mae: 0.3845 - val_loss: 0.1756 - val_mae: 0.2934
Epoch 41/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1919 - mae: 0.3043 - val_loss: 0.2061 - val_mae: 0.3248
Epoch 42/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2353 - mae: 0.3571 - val_loss: 0.2059 - val_mae: 0.3230
Epoch 43/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2321 - mae: 0.3412 - val_loss: 0.1912 - val_mae: 0.3115
Epoch 44/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2112 - mae: 0.3379 - val_loss: 0.2021 - val_mae: 0.3152
Epoch 45/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2331 - mae: 0.3503 - val_loss: 0.2297 - val_mae: 0.3453
Epoch 46/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2311 - mae: 0.3558 - val_loss: 0.1654 - val_mae: 0.2847
Epoch 47/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2112 - mae: 0.3358 - val_loss: 0.1746 - val_mae: 0.3053
Epoch 48/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2772 - mae: 0.3998 - val_loss: 0.3346 - val_mae: 0.4508
Epoch 49/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2554 - mae: 0.3622 - val_loss: 0.2881 - val_mae: 0.3954
Epoch 50/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2681 - mae: 0.3666 - val_loss: 0.5476 - val_mae: 0.5833
Epoch 51/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2558 - mae: 0.3513 - val_loss: 0.5649 - val_mae: 0.6213
Epoch 52/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3028 - mae: 0.3820 - val_loss: 0.3806 - val_mae: 0.4722
Epoch 53/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3009 - mae: 0.3791 - val_loss: 0.3099 - val_mae: 0.4053
Epoch 54/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2503 - mae: 0.3421 - val_loss: 0.2310 - val_mae: 0.3228
Epoch 55/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2655 - mae: 0.3590 - val_loss: 0.3282 - val_mae: 0.4396
Epoch 56/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2864 - mae: 0.3906 - val_loss: 0.2992 - val_mae: 0.3989
Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 46.

In [109]:
advanced_model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2003 - mae: 0.3270

[0.20034393668174744, 0.3270398676395416]

In [110]:
y_pred = advanced_model.predict(X_test)
y_pred[:5]

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

array([[ 0.22631872],
       [ 0.46245086],
       [ 0.08317474],
       [-0.21284477],
       [ 0.39730772]], dtype=float32)

In [111]:
y_pred = scaler_y.inverse_transform(y_pred)
y_pred[:5]

array([[71.22239],
       [74.74529],
       [69.08679],
       [64.67042],
       [73.77341]], dtype=float32)

In [112]:
advanced_model.save('artifacts/advanced_model.keras')